name = "road-racer-3d"
main = "worker.js"
compatibility_date = "2024-11-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "road-racer"
database_id = "PASTE-YOUR-D1-DATABASE-ID-HERE"
